### ISSUE TITLE
It doesn't wait for posting.

### ISSUE THREAD

**Issue by hexium310** [hexium310/Twiterian#7]
## Actual Behavior

It doesn't wait for posting.

## Expected Behavior

~~Disable textarea, button, and image click on posting.~~
It sends a Tweet in Background(Event) Pages.

**Comment by chitoku-k** [comment]
I think Twiterian should send a Tweet in background without disabling buttons.

**Comment by hexium310** [comment]
I forgot Background Pages.
It's a nice idea. :smile:
